### ISSUE TITLE
UITableView Support Checklist/Organization

### ISSUE THREAD

**Issue by amonshiz** [Instagram/IGListKit#692]
As [mentioned](https://github.com/Instagram/IGListKit/issues/584#issuecomment-294197821) by @jessesquires in Issue #584, there will need to be some separation of the work necessary to support `UITableView` and that which is just "rearranging the deck chairs".

Work that is necessary just for support:
- [x] Move `IGListAdapter`'s collection view data source and delegate implementations into category (done in #599)
- [x] Replace `[IGListCollectionContext sectionForSectionController:]` with `sectionIndex` property on section controllers (done in #671)
- [x] Add ` release-4.0-tableview-support` branch
- [ ] Protocol'ize the necessary interface to the presenting object, ie: the current collection view specific methods need to be in a category. This category could be something like `IGListCollectionPresentable` (naming TBD, but going to use that for this doc)
- [ ] Add empty conformance of `UICollectionView` to `IGListCollectionPresentable`
- [ ] Rewrite all current `UICollectionView *` properties/parameters to `UIView <IGListCollectionPresentable> *`
- [ ] Add `UITableView` conformance to `IGListCollectionPresentable`
  - This will include mimicking a number of behaviors that are not currently in `UITableView`, like batch updates
- [ ] Add tests to cover `UITableView`'s implementation of the protocol
- [ ] Add examples of `UITableView` usage

**Comment by futuretap** [comment]
Any news on this project?

**Comment by amonshiz** [comment]
This has been abandoned. It turned out there was no demand and the changes were not in the best interest of the project.

**Comment by futuretap** [comment]
Sad. There's no viable alternative for table views.
